/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../model/wheke3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube.geometry}
        material={nodes.Roundcube.material}
        // material={<shiftMaterial attach="material" />}
        // position={0,0,0}
      />
    </group>
  )
}

useGLTF.preload('../model/wheke3.glb')